<a href="https://colab.research.google.com/github/Otobi1/Back-to-Basics-A-Refresher-/blob/master/Back_to_Basics_CNNs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
## Set up 

import numpy as np 
import pandas as pd
import random 
import torch 
import torch.nn as nn

In [74]:
SEED = 1234

In [75]:
def set_seeds(seed = 1234):
  """Set seed for reproducibility."""
  np.random.seed(seed)
  random.seed(seed)
  torch.manual_seed(seed)
  torch.cuda.manual_seed(seed)
  torch.cuda.manual_seed_all(seed) # multi GPU

In [76]:
# Set seed for reproducibility 

set_seeds(seed=SEED)

In [77]:
# Set device 

cuda = True
device = torch.device("cuda" if (
    torch.cuda.is_available() and cuda) else "cpu")
torch.set_default_tensor_type("torch.FloatTensor")
if device.type == "cuda":
  torch.set_default_tensor_type("torch.cuda.FloatTensor")
print (device)

cuda


In [78]:
# Load data 
# - corpus of news article from http://groups.di.unipi.it/~gulli/AG_corpus_of_news_articles.html 

url = "https://raw.githubusercontent.com/GokuMohandas/madewithml/main/datasets/news.csv"
df = pd.read_csv(url, header = 0) # load
df = df.sample(frac = 1).reset_index(drop = True) # shuffle
df.head()

title  category
0  Sharon Accepts Plan to Reduce Gaza Army Operat...     World
1  Internet Key Battleground in Wildlife Crime Fight  Sci/Tech
2          July Durable Good Orders Rise 1.7 Percent  Business
3          Growing Signs of a Slowing on Wall Street  Business
4                        The New Faces of Reality TV     World

In [79]:
# Preprocessing 
# - to clean up the data, convert to lower text, remove filler words and filter using regex.

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

In [80]:
nltk.download("stopwords")
STOPWORDS = stopwords.words("english")
print (STOPWORDS[:5])
porter = PorterStemmer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
['i', 'me', 'my', 'myself', 'we']


In [81]:
def preprocess(text, stopwords = STOPWORDS):
  """Conditional preprocessing on our text unique to the task."""
  # Lower 
  text = text.lower()

  # Remove stopwords
  pattern = re.compile(r"\b(" + r"|".join(stopwords) + r")\b\s*")
  text = pattern.sub(" ", text)

  # Remove words in parenthesis
  text = re.sub(r"\([^)]*\)", " ", text)

  # Spacing and filters 
  text = re.sub(r"([-;;.,!?<=>])", r" \1 ", text)
  text = re.sub('[^A-Za-z0-9]+', ' ', text) # remove non alphanumeric characters
  text = re.sub(' +', ' ', text) # remove multiple spaces 
  text = text.strip()

  return text

In [82]:
# Sample 

text = "Great week for the NYSE"
preprocess(text = text)

'great week nyse'

In [83]:
# Apply to dataframe

preprocessed_df = df.copy()
preprocessed_df.title = preprocessed_df.title.apply(preprocess)
print (f"{df.title.values[0]}\n\n{preprocessed_df.title.values[0]}")

Sharon Accepts Plan to Reduce Gaza Army Operation, Haaretz Says

sharon accepts plan reduce gaza army operation haaretz says


In [84]:
# if you have preprocessing steps like standardisation, that are calculated, you need to separate the training an dtest set first before applying those operations. 
# this is because we cannot apply any knowledge gained from the test set accidentally (data leak during preprocessing/training). 
# - for global preprocessing steps like the functin above, where we arent learning anything from the data itself, we can perform them before splitting the data.

In [85]:
# Split the data 

import collections
from sklearn.model_selection import train_test_split

In [86]:
TRAIN_SIZE = 0.7
VAL_SIZE = 0.15
TEST_SIZE = 0.15

In [87]:
def train_val_test_split(X, y, train_size):
  """Split dataset into data split."""
  X_train, X_, y_train, y_ = train_test_split(X, y, train_size = TRAIN_SIZE, stratify = y)
  X_val, X_test, y_val, y_test = train_test_split(X_, y_, train_size = 0.5, stratify = y_)
  return X_train, X_val, X_test, y_train, y_val, y_test

In [88]:
# Data
X = preprocessed_df["title"].values 
y = preprocessed_df["category"].values

In [89]:
# Create data splits
X_train, X_val, X_test, y_train, y_val, y_test = train_val_test_split(
    X = X, y = y, train_size = TRAIN_SIZE)

print (f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print (f"X_val: {X_val.shape}, y_val: {y_val.shape}")
print (f"X_train: {X_test.shape}, y_test: {y_test.shape}")
print (f"Sample point: {X_train[0]} -> {y_train[0]}")


X_train: (84000,), y_train: (84000,)
X_val: (18000,), y_val: (18000,)
X_train: (18000,), y_test: (18000,)
Sample point: china battles north korea nuclear talks -> World


In [90]:
# Label Encoding 
# to encode the text labels into unique indices

import itertools

In [91]:
class LabelEncoder(object):
  """Label encoder for tag labels."""
  def __init__(self, class_to_index = {}):
    self.class_to_index = class_to_index
    self.index_to_class = {v: k for k, v in self.class_to_index.items()}
    self.classes = list(self.class_to_index.keys())

  def __len__(self):
    return len(self.class_to_index)

  def __str__(self):
    return f"<LabelEncoder(num_classes = {len(self)})>"
  
  def fit(self, y):
    classes = np.unique(y_train)
    for i, class_ in enumerate(classes):
      self.class_to_index[class_] = i
    self.index_to_class = {v: k for k, v in self.class_to_index.items()}
    self.classes = list(self.class_to_index.keys())
    return self

  def encode(self, y):
    encoded = np.zeros((len(y)), dtype = int)
    for i, item in enumerate(y):
      encoded[i] = self.class_to_index[item]
    return encoded

  def decode(self, y):
    classes = []
    for i, item in enumerate(y):
      classes.append(self.index_to_class[item])
    return classes

  def save(self, fp):
    with open(fp, "w") as fp:
      contents = {"class_to_index": self.class_to_index}
      json.dump(contents, fp, indent = 4, sort_keys = False)

  @classmethod
  def load(cls, fp):
    with open(fp, "r") as fp:
      kwargs = json.load(fp = fp)
    return cls(**kwargs)

In [92]:
# Encode 

label_encoder = LabelEncoder()
label_encoder.fit(y_train)
NUM_CLASSES = len(label_encoder)
label_encoder.class_to_index

{'Business': 0, 'Sci/Tech': 1, 'Sports': 2, 'World': 3}

In [93]:
# Converting labels to tokens 

print (f"y_train[0]: {y_train[0]}")

y_train = label_encoder.encode(y_train)
y_val = label_encoder.encode(y_val)
y_test = label_encoder.encode(y_test)

print (f"y_train[0]: {y_train[0]}")

y_train[0]: World
y_train[0]: 3


In [94]:
# Class weights 

counts = np.bincount(y_train)
class_weights = {i: 1.0/count for i, count in enumerate(counts)}
print (f"counts: {counts}\nweights: {class_weights}")

counts: [21000 21000 21000 21000]
weights: {0: 4.761904761904762e-05, 1: 4.761904761904762e-05, 2: 4.761904761904762e-05, 3: 4.761904761904762e-05}


In [95]:
# Tokenizer 

import json
from collections import Counter
from more_itertools import take

In [96]:
class Tokeniser(object):
  def __init__(self, char_level, num_tokens = None,
               pad_token = "<PAD>", oov_token = "<UNK>", 
               token_to_index = None):
    self.char_level = char_level
    self.separator = " " if self.char_level else " "
    if num_tokens: num_tokens -= 2 # pad + unk tokens
    self.num_tokens = num_tokens
    self.oov_token = oov_token
    if not token_to_index:
      token_to_index = {"<PAD>": 0, "<UNK>": 1}
    self.token_to_index = token_to_index
    self.index_to_token = {v: k for k, v in self.token_to_index.items()}

  def __len__(self):
    return len(self.token_to_index)

  def __str__(self):
    return f"<Tokeniser(num_tokens = {len(self)})>"

  def fit_on_texts(self, texts):
    if self.char_level:
      all_tokens = [token for text in texts for token in text]
    if not self.char_level:
      all_tokens = [token for text in texts for token in text.split(" ")]
    counts = Counter(all_tokens).most_common(self.num_tokens)
    self.min_token_freq = counts[-1][1]
    for token, count in counts:
      index = len(self)
      self.token_to_index[token] = index
      self.index_to_token[index] = token
    return self

  def texts_to_sequence(self, texts):
    sequences = []
    for text in texts:
      if not self.char_level:
        text = text.split(' ')
      sequence = []
      for token in text: 
        sequence.append(self.token_to_index.get(
            token, self.token_to_index[self.oov_token]))
      sequences.append(np.asarray(sequence))
    return sequences
  
  def sequences_to_texts(self, sequences):
    texts = []
    for sequence in sequences:
      text = []
      for index in sequence :
        text.append(self.index_to_token.get(index, self.oov_token))
      texts.append(self.separator.join([token for token in text]))
    return texts
  
  def save(self, fp):
    with open(fp, "w") as fp:
      contents = {
          "char_level": self.char_level, 
          "oov_token": self.oov_token, 
          "token_to_index": self.token_to_index
      }
      json.dump(contents, fp, indent = 4, sort_keys = False)

  @classmethod
  def load(cls, fp):
    with open(fp, "r") as fp:
      kwargs = json.load(fp = fp)
    return cls(**kwargs)

In [97]:
## - we will restrict the number of tokens in our tokenizer to the top 500 most frequent tokens (stop words already removed)
# -- because the full vocabulary (approx 30k) is too large to run on google colab

# ** it is important that we are only using the training data split because during inference, the model will not always know every token
# -- so it is important to replicate that scenario with the validation and test split. 

In [98]:
# Tokenise

tokeniser = Tokeniser(char_level = False, num_tokens = 500)
tokeniser.fit_on_texts(texts = X_train)
VOCAB_SIZE = len(tokeniser)

print (tokeniser)

<Tokeniser(num_tokens = 500)>


In [99]:
# Sample of tokens 

print (take(5, tokeniser.token_to_index.items()))
print (f"least freq tokens freq: {tokeniser.min_token_freq}") # use this to adjust num tokens

[('<PAD>', 0), ('<UNK>', 1), ('39', 2), ('b', 3), ('gt', 4)]
least freq tokens freq: 166


In [100]:
# Convert texts to sequences of indices 

X_train = tokeniser.texts_to_sequence(X_train)
X_val = tokeniser.texts_to_sequence(X_val)
X_test = tokeniser.texts_to_sequence(X_test)

preprocessed_text = tokeniser.sequences_to_texts([X_train[0]])[0]
print ("Text to indices: \n"
    f" (preprocessed) -> {preprocessed_text}\n"
    f" (tokenised) -> {X_train[0]}")

Text to indices: 
 (preprocessed) -> china <UNK> north korea nuclear talks
 (tokenised) -> [ 16   1 285 142 114  24]


In [101]:
# One-hot Encoding 

# - Creates a binary column fro each unique value of each feature. 
# -- All the values for the token will be 0 except the index of that specific token

In [102]:
def to_categorical(seq, num_classes):
  """One-hot encode a sequence of tokens."""
  one_hot = np.zeros((len(seq), num_classes))
  for i, item in enumerate(seq):
    one_hot[i, item] = 1.
  return one_hot

In [103]:
# One-hot encoding 
print (X_train[0])
print (len(X_train[0]))
cat = to_categorical(seq = X_train[0], num_classes = len(tokeniser))

print (cat)
print (cat.shape)

[ 16   1 285 142 114  24]
6
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(6, 500)


In [104]:
# Convert tokens to one-hot

vocab_size = len(tokeniser)
X_train = [to_categorical(seq, num_classes = vocab_size) for seq in X_train]
X_val = [to_categorical(seq, num_classes = vocab_size) for seq in X_val]
X_test = [to_categorical(seq, num_classes = vocab_size) for seq in X_test]

In [105]:
# Padding 

# - all the inputs have varying lengths, but each batch needs to e uniformly shaped
# - we can use padding to make all the inputs in the batch the same length
# - the padding index will be 0

## ** one-hot encoding creates a batch of shape (N, max_seq_len, vocab_size) so we'll need to pad 3D sequences 

In [106]:
def pad_sequences(sequences, max_seq_len = 0):
  """Pad sequences to max length in sequence."""
  max_seq_len = max(max_seq_len, max(len(sequence) for sequence in sequences))
  num_classes = sequences[0].shape[-1]
  padded_sequences = np.zeros((len(sequences), max_seq_len, num_classes))
  for i, sequence in enumerate(sequences):
    padded_sequences[i][:len(sequence)] = sequence
  return padded_sequences

In [107]:
# 3D sequences 

print (X_train[0].shape, X_train[1].shape, X_train[2].shape)
padded = pad_sequences(X_train[0:3])
print (padded.shape)

(6, 500) (5, 500) (6, 500)
(3, 6, 500)


In [108]:
# Dataset
# - here we need to create datasets and dataloaders to be able to efficiently create batches with the data splits 

FILTER_SIZE = 1 # unigram

In [109]:
class Dataset(torch.utils.data.Dataset):
  def __init__(self, X, y, max_filter_size):
    self.X = X
    self.y = y
    self.max_filter_size = max_filter_size

  def __len__(self):
    return len(self.y)

  def __str__(self):
    return f"<Dataset(N = {len(self)})>"

  def __getitem__(self, index):
    X = self.X[index]
    y = self.y[index]
    return [X, y]

  def collate_fn(self, batch):
    """Processing on batch."""
    # Get inputs
    X = np.array(batch, dtype = object)[:, 0]
    y = np.stack(np.array(batch, dtype = object)[:, 1], axis = 0)

    # Pad sequences 
    X = pad_sequences(X, max_seq_len = self.max_filter_size)

    # Cast
    X = torch.FloatTensor(X.astype(np.int32))
    y = torch.LongTensor(y.astype(np.int32))

    return X, y

  def create_dataloader(self, batch_size, shuffle = False, drop_last = False):
    return torch.utils.data.DataLoader(
        dataset = self, batch_size = batch_size, collate_fn = self.collate_fn, 
        shuffle = shuffle, drop_last = drop_last, pin_memory = True)

In [110]:
# Create datasets for embedding 

train_dataset = Dataset(X = X_train, y = y_train, max_filter_size = FILTER_SIZE)
val_dataset = Dataset(X = X_val, y = y_val, max_filter_size = FILTER_SIZE)
test_dataset = Dataset(X = X_test, y = y_test, max_filter_size = FILTER_SIZE)
print ("Datasets: \n"
    f" Train dataset: {train_dataset.__str__()}\n"
    f" Val dataset: {val_dataset.__str__()}\n"
    f" Test dataset: {test_dataset.__str__()}\n"
    "Sample Point: \n"
    f" X: {test_dataset[0][0]}\n"
    f" y: {test_dataset[0][1]}")

Datasets: 
 Train dataset: <Dataset(N = 84000)>
 Val dataset: <Dataset(N = 18000)>
 Test dataset: <Dataset(N = 18000)>
Sample Point: 
 X: [[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
 y: 1


In [111]:
# Create dataloaders 

batch_size = 64
train_dataloader = train_dataset.create_dataloader(batch_size = batch_size)
val_dataloader = val_dataset.create_dataloader(batch_size = batch_size)
test_dataloader = test_dataset.create_dataloader(batch_size = batch_size)
batch_X, batch_y = next(iter(test_dataloader))
print ("Sample batch:\n"
    f" X: {list(batch_X.size())}\n"
    f" y: {list(batch_y.size())}\n"
    "Sample point:\n"
    f" X: {batch_X[0]}\n"
    f" y: {batch_y[0]}")

Sample batch:
 X: [64, 14, 500]
 y: [64]
Sample point:
 X: tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cpu')
 y: 1


In [112]:
# CNN - Convolutional Neural Networks 

# - Here we will learn about CNNs by applying them on 1D text data
# In the example below, we have a batch of N samples where wach sample has 8 characters and each char represented by an array of 10 values (vocab size = 10)
# - this gives our inputs the size (N, 8, 10)

# -- with PyTorch, when dealing with convs, the inputs X need to have the channels as the second dimension, so our inputs will be (N,10,8)

import math
import torch
import torch.nn as nn
import torch.nn.functional as F

In [113]:
# Assume all our inputs are padded to have the same words

batch_size = 64
max_seq_len = 8 # words per input
vocab_size = 10 # one hot size
x = torch.randn(batch_size, max_seq_len, vocab_size)
print (f" X:{x.shape}")
x = x.transpose(1, 2)
print (f" X:{x.shape}")

 X:torch.Size([64, 8, 10])
 X:torch.Size([64, 10, 8])


In [114]:
# At the core of CNNs are filters, also known as weights, kernels etc), which convolve (slide) across our input to extract relevant features. 
# the filters are initialised randomly but learn to act as feature extractors via parameter sharing.

# We will use a conv1d layer to process our inouts 

In [115]:
# Convolutional filters (Valid padding)

vocab_size = 10 # one-hot size
num_filters = 50 # num of filters 
filter_size = 3 # filters are 3 X 3 
stride = 1
padding = 0 # valid padding (no padding)
conv1 = nn.Conv1d(in_channels = vocab_size, out_channels = num_filters, 
                  kernel_size = filter_size, stride = stride, 
                  padding = padding, padding_mode = "zeros")
print ("conv: {}".format(conv1.weight.shape))

conv: torch.Size([50, 10, 3])


In [116]:
# Forward pass
z = conv1(x)
print (f"z: {z.shape}")

z: torch.Size([64, 50, 6])


In [117]:
# Now, we'll add padding so that the convolutional outputs are the same shape as our inputs. 
# - we want our output to have the same width as our input. 

In [118]:
# Convolutional filters (Same padding)

vocab_size = 10 # one-hot size
num_filters = 50 # num filters 
filter_size = 3 # filters are 3 X 3
stride = 1
conv = nn.Conv1d(in_channels = vocab_size, out_channels = num_filters, 
                 kernel_size = filter_size, stride = stride)
print ("conv: {}".format(conv.weight.shape))

conv: torch.Size([50, 10, 3])


In [119]:
# Same padding 

padding_left = int((conv.stride[0] * (max_seq_len-1) - max_seq_len + filter_size) / 2)
padding_right = int(math.ceil((conv.stride[0] * (max_seq_len - 1) - max_seq_len + filter_size) / 2))
print (f"padding: {(padding_left, padding_right)}")

padding: (1, 1)


In [120]:
# Forward pass 

z = conv(F.pad(x, (padding_left, padding_right)))
print (f"z: {z.shape}")

z: torch.Size([64, 50, 8])


In [121]:
# Pooling 

# - the result of the convolving filters on an input is a feature map. Due to the nature of convolution and overlaps,our feature map will have lots of redundant information.
# - Pooling is a way to summarise a high-dimensional feature map into a lower dimensional one for simplified downstream computation. 
# -- the pooling operation can be the max value, average etc

# Max pooling 

pool_output = F.max_pool1d(z, z.size(2))
print ("Size: {}".format(pool_output.shape))

Size: torch.Size([64, 50, 1])


In [122]:
# Batch normalisation 

# - this is an operation that will standardise the activations from the previous layer 
# recall that we've previously standardised our inputs so that the model can optimise quickly with larger learning learning rates
# - here we will use the same concept  but we will continue to maintain standardised values throughout the forward pass to further aid optimisation

In [123]:
batch_norm = nn.BatchNorm1d(num_features = num_filters)
z = batch_norm(conv(x)) # applied to activations (after conv layer & before pooling)
print (f"z: {z.shape}")

z: torch.Size([64, 50, 6])


In [124]:
# Mean and std before batchnorm
print (f"mean: {torch.mean(conv1(x)):.2f}, std: {torch.std(conv(x)):.2f}")

mean: 0.01, std: 0.57


In [125]:
# Mean and std after batchnorm
print (f"mean: {torch.mean(z):.2f}, std: {torch.std(z):.2f}")

mean: 0.00, std: 1.00


In [126]:
# Modelling 

# First, tokenise the inputs (batch_size, max_seq_len)
# Then, one-hot encode the tokenised inputs(batch_size, max_seq_len, vocab_size)
# After, apply, conv filters (filter_size, vocab_size, num_filters) then, batch norm
# Then, apply 1D global max pooling which will extract the most rlevant information from th feature maps for making the decision
# After, feed the pool outputs to a fully connected layer with dropout
# Last, we use one more fully connected layer with Softmax to derive class probabilities

In [127]:
NUM_FILTERS = 50
HIDDEN_DIM = 100
DROPOUT_P = 0.1

In [128]:
class CNN(nn.Module):
  def __init__(self, vocab_size, num_filters, filter_size, hidden_dim, dropout_p, num_classes):
    super(CNN, self).__init__()

    # Convolutional filters 
    self.filter_size = filter_size
    self.conv = nn.Conv1d(
        in_channels = vocab_size, out_channels = num_filters, 
        kernel_size = filter_size, stride = 1, padding = 0, padding_mode = "zeros")
    self.batch_norm = nn.BatchNorm1d(num_features = num_filters)

    # Fully Connected layers
    self.fc1 = nn.Linear(num_filters, hidden_dim)
    self.dropout_p = nn.Dropout(dropout_p)
    self.fc2 = nn.Linear(hidden_dim, num_classes)

  def forward(self, inputs, channel_first = False, apply_softmax = False):
    # Rearrange input so num_channels is in dim 1 (N, C, L)
    x_in, = inputs
    if not channel_first:
      x_in = x_in.transpose(1, 2)

    # Padding for SAME padding 
    max_seq_len = x_in.shape[2]
    padding_left = int((self.conv.stride[0] * (max_seq_len -1) - max_seq_len + self.filter_size) / 2)
    padding_right = int(math.ceil((self.conv.stride[0] * (max_seq_len) - max_seq_len + self.filter_size) / 2))

    # Conv outputs 
    z = self.conv(F.pad(x_in, (padding_left, padding_right))) 
    z = F.max_pool1d(z, z.size(2)).squeeze(2)

    # Fully connected layer 
    z = self.fc1(z)
    z = self.dropout_p(z)
    y_pred = self.fc2(z)

    if apply_softmax:
      y_pred = F.softmax(y_pred, dim = 1)
    return y_pred

In [129]:
# Initialising the model 

model = CNN(vocab_size = VOCAB_SIZE, num_filters = NUM_FILTERS, filter_size = FILTER_SIZE,
            hidden_dim = HIDDEN_DIM,dropout_p = DROPOUT_P, num_classes = NUM_CLASSES )
model = model.to(device) # set device
print (model.named_parameters)

<bound method Module.named_parameters of CNN(
  (conv): Conv1d(500, 50, kernel_size=(1,), stride=(1,))
  (batch_norm): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc1): Linear(in_features=50, out_features=100, bias=True)
  (dropout_p): Dropout(p=0.1, inplace=False)
  (fc2): Linear(in_features=100, out_features=4, bias=True)
)>


In [130]:
# Training 

from torch.optim import Adam

In [131]:
LEARNING_RATE = 1e-3
PATIENCE = 5
NUM_EPOCHS = 10

In [132]:
class Trainer(object):
  def __init__(self, model, device, loss = None, optimiser = None, scheduler = None):
    
    # Set params 
    self.model = model 
    self.device = device 
    self.loss = loss
    self.optimiser = optimiser
    self.scheduler = scheduler

  def train_step(self, dataloader):
    """Train step."""
    # Set model to train mode 
    self.model.train()
    loss = 0.0

    # Iterate over train batches
    for i, batch in enumerate(dataloader):

      # Step
      batch = [item.to(self.device) for item in batch] # Set device 
      inputs, targets = batch[:-1], batch[-1]
      self.optimiser.zero_grad() # Reset gradients 
      z = self.model(inputs) # Forward pass
      J = self.loss(z, targets) # Define loss
      J.backward() # Backward pass 
      self.optimiser.step() # Update weights

      # Cumulative metrics 
      loss += (J.detach().item() - loss) / (i + 1)

    return loss
  
  def eval_step(self, dataloader):
    """Validation of test step."""
    # Set model to eval mode
    self.model.eval()
    loss = 0.0
    y_trues, y_probs = [], []

    # Iterate over the val batches 
    with torch.no_grad():
      for i, batch in enumerate(dataloader):

        # Step
        batch = [item.to(self.device) for item in batch] # Set device
        inputs, y_true = batch[:-1], batch[-1]
        z = self.model(inputs) # Forward pass
        J = self.loss(z, y_true).item()

        # Cumulative Metrics 
        loss += (J - loss) / (i + 1)

        # Store outputs 
        y_prob = torch.sigmoid(z).cpu().numpy()
        y_probs.extend(y_prob)
        y_trues.extend(y_true.cpu().numpy())
    
    return loss, np.vstack(y_trues), np.vstack(y_probs)

  def predict_step(self, dataloader):
    """Prediction step."""
    # Set model to eval mode
    self.model.eval()
    y_probs = []

    # Iterate over the val batches
    with torch.no_grad():
      for i, batch in enumerate(dataloader):

        # Forward pass w/ inputs 
        inputs, targets = batch[:-1], batch[-1]
        y_prob = self.model(inputs, apply_softmax = True)

        # Store outputs
        y_probs.extend(y_prob)

    return np.vstack(y_probs)

  def train(self, num_epochs, patience, train_dataloader, val_dataloader):
    best_val_loss = np.inf
    for epoch in range(num_epochs):

      # Steps
      train_loss = self.train_step(dataloader = train_dataloader)
      val_loss, _, _ = self.eval_step(dataloader = val_dataloader)

      # Early stopping
      if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model = self.model
        _patience = patience # Reset patience 
      else:
        _patience -= 1
      if not _patience: # 0
        print ("Stopping early!")
        break

      # Logging
      print (
          f"Epoch: {epoch +1} | "
          f"train_loss: {train_loss:.5f}, "
          f"val_loss: {val_loss:.5f}, "
          f"lr: {self.optimiser.param_groups[0]['lr']:.2E}, "
          f"_patience: {_patience}"
      )
    return best_model


In [133]:
# Define loss

class_weights_tensor = torch.Tensor(list(class_weights.values())).to(device)
loss = nn.CrossEntropyLoss(weight = class_weights_tensor)

In [134]:
# Define optimiser and scheduler

optimiser = Adam(model.parameters(), lr = LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimiser, mode = 'min', factor = 0.1, patience = 3)

In [135]:
# Trainer module

trainer = Trainer(
    model = model, device = device, loss = loss, 
    optimiser = optimiser, scheduler = scheduler)

In [136]:
# Train
best_model = trainer.train(
    NUM_EPOCHS, PATIENCE, train_dataloader, val_dataloader)

Epoch: 1 | train_loss: 0.87454, val_loss: 0.79113, lr: 1.00E-03, _patience: 5
Epoch: 2 | train_loss: 0.78471, val_loss: 0.78694, lr: 1.00E-03, _patience: 5
Epoch: 3 | train_loss: 0.77998, val_loss: 0.78519, lr: 1.00E-03, _patience: 5
Epoch: 4 | train_loss: 0.77678, val_loss: 0.78441, lr: 1.00E-03, _patience: 5
Epoch: 5 | train_loss: 0.77483, val_loss: 0.78339, lr: 1.00E-03, _patience: 5
Epoch: 6 | train_loss: 0.77326, val_loss: 0.78268, lr: 1.00E-03, _patience: 5
Epoch: 7 | train_loss: 0.77227, val_loss: 0.78248, lr: 1.00E-03, _patience: 5
Epoch: 8 | train_loss: 0.77135, val_loss: 0.78251, lr: 1.00E-03, _patience: 4
Epoch: 9 | train_loss: 0.77042, val_loss: 0.78203, lr: 1.00E-03, _patience: 5
Epoch: 10 | train_loss: 0.76958, val_loss: 0.78201, lr: 1.00E-03, _patience: 5


In [137]:
# Evaluation 

import json
from pathlib import Path
from sklearn.metrics import precision_recall_fscore_support

In [138]:
def get_performance(y_true, y_pred, classes):
  """Per-class performance metrics."""
  # Get metrics 
  performance = {"overall": {}, "class": {}}
  metrics = precision_recall_fscore_support(y_true, y_pred)

  # Overall performance 
  performance["overall"]["precision"] = np.mean(metrics[0])
  performance["overall"]["recall"] = np.mean(metrics[1])
  performance["overall"]["f1"] = np.mean(metrics[2])
  performance["overall"]["num_samples"] = np.float64(np.sum(metrics[3]))

  # Per class performance
  for i in range(len(classes)):
    performance["class"][classes[i]] = {
        "precision": metrics[0][i], 
        "recall": metrics[1][i], 
        "f1": metrics[2][i], 
        "num_samples": np.float64(metrics[3][i])
    }
  return performance

In [139]:
# get predictions 

test_loss, y_true, y_prob = trainer.eval_step(dataloader = test_dataloader)
y_pred = np.argmax(y_prob, axis = 1)

In [140]:
# Determine performance 
performance = get_performance(
    y_true = y_test, y_pred = y_pred, classes = label_encoder.classes)
print (json.dumps(performance["overall"], indent = 2))

{
  "precision": 0.7115579309819231,
  "recall": 0.6917222222222221,
  "f1": 0.6911547384674819,
  "num_samples": 18000.0
}


In [141]:
# Save artifacts 

dir = Path("cnn")
dir.mkdir(parents = True, exist_ok = True)
label_encoder.save(fp = Path(dir, "label_encoder.json"))
tokeniser.save(fp = Path(dir, "tokeniser.json"))
torch.save(best_model.state_dict(), Path(dir, "model.pt"))
with open(Path(dir, "performance.json"), "w") as fp:
  json.dump(performance, indent = 2, sort_keys = False, fp = fp)

In [150]:
# Inference 
def get_probability_distribution(y_prob, classes):
  """Create a dict of class probabilities from an array."""
  results = {}
  for i, class_ in enumerate(classes):
    results[class_] = np.float64(y_prob[i])
  sorted_results = {k: v for k, v in sorted(
      results.items(), key = lambda item: item[1], reverse = True)}
  return sorted_results


In [151]:
# Load artifacts
device = torch.device("cpu")
label_encoder = LabelEncoder.load(fp=Path(dir, 'label_encoder.json'))
tokeniser = Tokeniser.load(fp=Path(dir, 'tokeniser.json'))
model = CNN(
    vocab_size=VOCAB_SIZE, num_filters=NUM_FILTERS, filter_size=FILTER_SIZE,
    hidden_dim=HIDDEN_DIM, dropout_p=DROPOUT_P, num_classes=NUM_CLASSES)
model.load_state_dict(torch.load(Path(dir, 'model.pt'), map_location=device))
model.to(device)

CNN(
  (conv): Conv1d(500, 50, kernel_size=(1,), stride=(1,))
  (batch_norm): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc1): Linear(in_features=50, out_features=100, bias=True)
  (dropout_p): Dropout(p=0.1, inplace=False)
  (fc2): Linear(in_features=100, out_features=4, bias=True)
)

In [152]:
# Initialise trainer 

trainer = Trainer(model = model, device = device)

In [153]:
# Dataloader 

text = "What a day for the new york stock market to go burst!"
sequences = tokeniser.texts_to_sequence([preprocess(text)])
print (tokeniser.sequences_to_texts(sequences))
X = [to_categorical(seq, num_classes = len(tokeniser)) for seq in sequences]
y_filler = label_encoder.encode([label_encoder.classes[0]] * len(X))
dataset = Dataset(X = X, y = y_filler, max_filter_size = FILTER_SIZE)
dataloader = dataset.create_dataloader(batch_size = batch_size)

['day new <UNK> stock market go <UNK>']


In [154]:
# Inference

y_prob = trainer.predict_step(dataloader)
y_pred = np.argmax(y_prob, axis = 1)
label_encoder.decode(y_pred)

['Business']

In [155]:
# Class distributions

prob_dist = get_probability_distribution(y_prob = y_prob[0], classes = label_encoder.classes)
print (json.dumps(prob_dist, indent = 2))

{
  "Business": 0.8190300464630127,
  "Sci/Tech": 0.16043992340564728,
  "World": 0.014267615973949432,
  "Sports": 0.006262409966439009
}
