<a href="https://colab.research.google.com/github/Otobi1/Back-to-Basics-A-Refresher-/blob/master/Back_to_Basics_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Set seed for reproducibility (so that we receive the exact same results every time)

np.random.seed(seed = 1234)

In [4]:
# Scalar: a scalar is a 0-D (zero dimension)  tensor. Its a single value

x = np.array(6)

print ("x: ", x)
print ("x ndim: ", x.ndim) # Number of dimensions
print ("x shape: ", x.shape) # dimensions
print ("x size: ", x.size) # size of elements
print ("x dtype: ", x.dtype) # data type

x:  6
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [5]:
# Vector : its a 1-D (1 dimension) tensor. It is a row or column of values

x = np.array([1.3, 2.2, 1.7])

print ("x: ", x)
print ("x ndim: ", x.ndim) # Number of dimensions
print ("x shape: ", x.shape) # dimensions
print ("x size: ", x.size) # size of elements
print ("x dtype: ", x.dtype) # data type (notice the float data type)

x:  [1.3 2.2 1.7]
x ndim:  1
x shape:  (3,)
x size:  3
x dtype:  float64


In [6]:
# Matrix: it is a 2-D tensor(2 dimension tensor). It is an array of rows and columns of values

x = np.array([[1,2], [3, 4]])

print ("x:\n", x)
print ("x ndim: ", x.ndim) # Number of dimensions
print ("x shape: ", x.shape) # dimensions
print ("x size: ", x.size) # size of elements
print ("x dtype: ", x.dtype) # data type

x:
 [[1 2]
 [3 4]]
x ndim:  2
x shape:  (2, 2)
x size:  4
x dtype:  int64


In [7]:
# 3-D Tensor

x = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

print ("x:\n", x)
print ("x ndim: ", x.ndim) # Number of dimensions
print ("x shape: ", x.shape) # dimensions
print ("x size: ", x.size) # size of elements
print ("x dtype: ", x.dtype) # data type

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape:  (2, 2, 2)
x size:  8
x dtype:  int64


In [8]:
## Functions 
# NumPy also comes with some functions that facilitate the creation of tensors quickly 

print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)): \n", np.ones((2,2)))
print ("np.eye((2)): \n", np.eye((2))) # identity matrix
print ("np.random.random((2,2)): \n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)): 
 [[1. 1.]
 [1. 1.]]
np.eye((2)): 
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)): 
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


In [9]:
## Indexing 
# We can extract specific values from our tensors using indexing
# Keep in mind that when indexing, the row and column indices start at 0. 
# Also we can use negative indices as we have lists (where -1, is the last item on the list)

# indexing 

x = np.array([1,2,3])
print ("x: ", x)
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [10]:
# Slicing 

x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print (x)
print ("x column 1: ", x[:,1])
print ("x row 0: ", x[0, :])
print ("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [11]:
# Integer array indexing 

print (x)
rows_to_get = np.array([0,1,2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
# combine sequences above to get values to get
print ("indexed values: ", x[rows_to_get, cols_to_get])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [12]:
# Boolean array indexing 

x = np.array([[1, 2], [3,4], [5, 6]])

print ("x: \n", x)
print ("x > 2: \n ", x > 2)
print ("x[x > 2]: \n", x[x > 2])

x: 
 [[1 2]
 [3 4]
 [5 6]]
x > 2: 
  [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]: 
 [3 4 5 6]
