<a href="https://colab.research.google.com/github/Otobi1/Back-to-Basics-A-Refresher-/blob/master/Back_to_Basics_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the needed libraries 

import numpy as np
import torch 

print ("Libraries successfully imported!")

Libraries successfully imported!


In [2]:
# Set seed for reproducibility 

SEED = 1234
np.random.seed(seed = SEED)
torch.manual_seed(SEED)

In [3]:
# Creating a random tensor 

x = torch.randn(2,3) # normal distribution (rand(2,3) -> uniform distribution)

print (f"Type: {x.type()}")
print (f"Size: {x.shape}")
print (f"Values: \n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [4]:
# Zero and ones tensor 

x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# List -> Tensor
x = torch.Tensor([[1,2,3], [4,5,6]])

print (f"Size: {x.shape}")
print (f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
# Numpy array -> Tensor

x = torch.Tensor(np.random.rand(2,3))

print (f"Size: {x.shape}")
print (f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [7]:
# Changing tensor type

x = torch.Tensor(3,4)
print (f"Type: {x.type()}")
x = x.long()
print (f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor


In [ ]:
## Operations 