<a href="https://colab.research.google.com/github/Otobi1/Back-to-Basics-A-Refresher-/blob/master/Back_to_Basics_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the needed libraries 

import numpy as np
import torch 

print ("Libraries successfully imported!")

Libraries successfully imported!


In [2]:
# Set seed for reproducibility 

SEED = 1234
np.random.seed(seed = SEED)
torch.manual_seed(SEED)

In [3]:
# Creating a random tensor 

x = torch.randn(2,3) # normal distribution (rand(2,3) -> uniform distribution)

print (f"Type: {x.type()}")
print (f"Size: {x.shape}")
print (f"Values: \n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [4]:
# Zero and ones tensor 

x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# List -> Tensor
x = torch.Tensor([[1,2,3], [4,5,6]])

print (f"Size: {x.shape}")
print (f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
# Numpy array -> Tensor

x = torch.Tensor(np.random.rand(2,3))

print (f"Size: {x.shape}")
print (f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [7]:
# Changing tensor type

x = torch.Tensor(3,4)
print (f"Type: {x.type()}")
x = x.long()
print (f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor


In [8]:
## Operations 
# - Addition

x = torch.randn(2,3)
y = torch.randn(2,3)

z = x + y

print (f"Size: {z.shape}")
print (f"Values: \n{z}")

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0761, -0.6775, -0.3988],
        [ 3.0633, -0.1589,  0.3514]])


In [9]:
# - Dot product

x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x, y)

print (f"Size: {z.shape}")
print (f"Values: \n{z}")

Size: torch.Size([2, 2])
Values: 
tensor([[ 1.0796, -0.0759],
        [ 1.2746, -0.5134]])


In [10]:
# - Transpose

x = torch.randn(2,3)

print (f"Size: {x.shape}")
print (f"Values: \n{x}")

y = torch.t(x)

print (f"Size: {y.shape}")
print (f"Values: \n{y}")

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.8042, -0.1383,  0.3196],
        [-1.0187, -1.3147,  2.5228]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8042, -1.0187],
        [-0.1383, -1.3147],
        [ 0.3196,  2.5228]])


In [11]:
# - Reshape

x = torch.randn(2,3)
z = x.view(3,2)

print (f"Size: {z.shape}")
print (f"Values: \n{z}")

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.4501,  0.2709],
        [-0.8087, -0.0217],
        [-1.0413,  0.0702]])


In [12]:
# - Dangers of reshaping (unintended consequences)

# https://madewithml.com/courses/ml-foundations/pytorch/

In [13]:
# - Dimensional operations 

x = torch.randn(2,3)

print (f"Values: \n{x}")
y = torch.sum(x, dim = 0) # add each row's value for every column
print (f"Values: \n{y}")
z = torch.sum(x, dim = 1) # add each columns value for every row
print (f"Values: \n{z}")

Values: 
tensor([[ 0.5797, -0.0599,  0.1816],
        [-0.6797, -0.2567, -1.8189]])
Values: 
tensor([-0.1000, -0.3166, -1.6373])
Values: 
tensor([ 0.7013, -2.7553])


In [14]:
# Indexing, Slicing and Joining 

# - Here we review how to extract, separate and join values with tensors 

x = torch.randn(3,4)

print (f"x: \n{x}")
print (f"x[:1]: \n{x[:1]}")
print (f"x[:1, 1:3]: \n{x[:1, 1:3]} ")

x: 
tensor([[ 0.2111,  0.3372,  0.6638,  1.0397],
        [ 1.8434,  0.6588, -0.2349, -0.0306],
        [ 1.7462, -0.0722, -1.6794, -1.7010]])
x[:1]: 
tensor([[0.2111, 0.3372, 0.6638, 1.0397]])
x[:1, 1:3]: 
tensor([[0.3372, 0.6638]]) 


In [15]:
# Select with dimensional indices 

x = torch.randn(2,3)
print (f"Values: \n{x}")

col_indices = torch.LongTensor([0,2])
chosen = torch.index_select(x, dim = 1, index = col_indices) # values from col 0 & 2
print(f"Values: \n{chosen}")

row_indices = torch.LongTensor([0,1])
col_indices = torch.LongTensor([0,2])
chosen = x[row_indices, col_indices] # values from (0,0) & (2,1)
print (f"Values: \n{chosen}")

Values: 
tensor([[ 0.6486,  1.7653,  1.0812],
        [ 1.2436,  0.8971, -0.0784]])
Values: 
tensor([[ 0.6486,  1.0812],
        [ 1.2436, -0.0784]])
Values: 
tensor([ 0.6486, -0.0784])


In [ ]:
# Concatenation